FROM node:alpine AS build-stage
WORKDIR /app
COPY package.json .
RUN npm uninstall react-scripts
RUN npm install react-scripts
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
