version: '3.8'

services:
   app:
     image: app-prod-i
     build:
       dockerfile: Dockerfile.prod
     container_name: app-prod-c
     ports:
       - "8080:80"
     environment:
       - NODE_ENV=production
