version: '3.8'

services:
    app:
      image: app.dev-i
      build:
        dockerfile: Dockerfile.dev
      container_name: app-dev-c
      restart: unless-stopped
      volumes:
        - ./Reactjs_app_Dev-Env:/app
        - node_modules:/app/node_modules
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=development
volumes:
  node_modules:
