FROM node:alpine AS build
WORKDIR /app
COPY package.json /app/package.json
RUN npm uninstall react-scripts
RUN npm install react-scripts
COPY . ./app
RUN npm run build


FROM nginx
COPY --from=build /app/build/ /usr/share/nginx/html
