version: '3.8'

services:
   app:
     image: app-prod-i
     build:
       dockerfile: Dockerfile.prod
     container_name: app-prod-c
     restart: unless-stopped
     ports:
       - "3000:80"
     environment:
       - NODE_ENV=production
