name: My GitHub Actions Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on:  ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "Hello from GitHub Actions!"

